/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import adminpanel.client;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author anirudhhenrylal
 */

public class signup extends javax.swing.JFrame {

  
      Connection con;
    public signup() {
        initComponents();
        getContentPane () . setBackground (Color. black) ;
         String url="jdbc:mysql://localhost:3306/test";
        String user="root";
        String pass="";
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","1234");
            // select();
        }catch(SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        j6 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        jsubmit = new javax.swing.JButton();
        jsubmit1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jsubmit2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("AppleMyungjo", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(196, 196, 144));
        jLabel1.setText("Register Yourself ");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(196, 196, 144));
        jLabel2.setText("Frist Name:");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(196, 196, 144));
        jLabel3.setText("Last Name:");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(196, 196, 144));
        jLabel4.setText("Password:");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(196, 196, 144));
        jLabel5.setText("Adddress:");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(196, 196, 144));
        jLabel6.setText("E-mail:");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(196, 196, 144));
        jLabel7.setText("Phone No. :");

        j1.setBackground(new java.awt.Color(0, 0, 0));
        j1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        j1.setForeground(new java.awt.Color(182, 182, 134));
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j2.setBackground(new java.awt.Color(0, 0, 0));
        j2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        j2.setForeground(new java.awt.Color(182, 182, 134));

        j3.setBackground(new java.awt.Color(0, 0, 0));
        j3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        j3.setForeground(new java.awt.Color(182, 182, 134));

        j4.setBackground(new java.awt.Color(0, 0, 0));
        j4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        j4.setForeground(new java.awt.Color(182, 182, 134));

        j6.setBackground(new java.awt.Color(0, 0, 0));
        j6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        j6.setForeground(new java.awt.Color(182, 182, 134));

        j5.setBackground(new java.awt.Color(0, 0, 0));
        j5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        j5.setForeground(new java.awt.Color(182, 182, 134));

        jsubmit.setBackground(new java.awt.Color(0, 0, 0));
        jsubmit.setFont(new java.awt.Font("Adelle Sans Devanagari", 1, 18)); // NOI18N
        jsubmit.setForeground(new java.awt.Color(178, 178, 130));
        jsubmit.setText("Submit");
        jsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmitActionPerformed(evt);
            }
        });

        jsubmit1.setBackground(new java.awt.Color(0, 0, 0));
        jsubmit1.setFont(new java.awt.Font("Adelle Sans Devanagari", 1, 18)); // NOI18N
        jsubmit1.setForeground(new java.awt.Color(178, 178, 130));
        jsubmit1.setText("Reset");
        jsubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmit1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(178, 178, 130));
        jLabel8.setText("For More Information Contact on: 9828012543, 9988552211 or At eventmange@gmail.com");

        jsubmit2.setBackground(new java.awt.Color(0, 0, 0));
        jsubmit2.setFont(new java.awt.Font("Adelle Sans Devanagari", 1, 18)); // NOI18N
        jsubmit2.setForeground(new java.awt.Color(178, 178, 130));
        jsubmit2.setText("Back");
        jsubmit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmit2ActionPerformed(evt);
            }
        });

        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Buyer");

        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Merchant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addGap(70, 70, 70)
                .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jsubmit2)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jsubmit1)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jsubmit)))
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsubmit2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsubmit1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(639, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1ActionPerformed

    private void jsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmitActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
                
//                
//                if (jRadioButton1.isSelected()){
//                     try {
//            // TODO add your handling code here:
//            java.sql.Statement st = con.createStatement();
//            String sql ="insert into client ( name , username , password , email , address , phone_number) values ('"+j1.getText()+"','"+j2.getText()+"','"+j3.getText()+"','"+j4.getText()+"','"+j5.getText()+"','"+j6.getText()+"') ";
//            
//            boolean b = st.execute(sql);
//           
//            if(!b)
//            {
//                JOptionPane.showMessageDialog(this, "inserted");
//            }
//            else{
//                JOptionPane.showMessageDialog(this, "incorrect entry");
//            }
//         
//        } catch (SQLException ex) {
//            Logger.getLogger(client.class.getName()).log(Level.SEVERE, null, ex);
//        }
//                signin sp1 = new signin ();
//                sp1.show();
//        
//                }
//                 if (jRadioButton2.isSelected()){
//                      mrechantinfo sp = new mrechantinfo ();
//        sp.show();
//        
//        dispose();
//                 }   
//         
//        dispose();
if (jRadioButton1.isSelected()) {
    try {
        String sql = "INSERT INTO client (name, username, password, email, address, phone_number) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement statement= con.prepareStatement(sql);
        
        statement.setString(1, j1.getText());
        statement.setString(2, j2.getText());
        statement.setString(3, j3.getText());
        statement.setString(4, j4.getText());
        statement.setString(5, j5.getText());
        statement.setString(6, j6.getText());
        
        int rowsInserted = statement.executeUpdate();

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Inserted");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to insert");
        }
    } catch (SQLException ex) {
        Logger.getLogger(client.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    
    signin sp1 = new signin();
    sp1.show();
} else if (jRadioButton2.isSelected()) {
    mrechantinfo sp = new mrechantinfo();
    sp.show();
    dispose();
}else{
    signup s= new signup();
    s.show();
}

dispose();


    }//GEN-LAST:event_jsubmitActionPerformed

    private void jsubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmit1ActionPerformed
        // TODO add your handling code here:
        j1.setText(null);
        j2.setText(null);
        j3.setText(null);
        j4.setText(null);
        j6.setText(null);
        j5.setText(null);
    }//GEN-LAST:event_jsubmit1ActionPerformed

    private void jsubmit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmit2ActionPerformed
        // TODO add your handling code here:
         startpage sp1 = new startpage ();
        sp1.show();
        
        dispose();
    }//GEN-LAST:event_jsubmit2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton jsubmit;
    private javax.swing.JButton jsubmit1;
    private javax.swing.JButton jsubmit2;
    // End of variables declaration//GEN-END:variables
}
